### ISSUE TITLE
Add bitrise CI configuration option

### ISSUE THREAD

**Issue by MPuhakka** [solinor/react-native-ci#15]
- Add support for multiple possible CI provider configurations
- add bitrise CI support

**Comment by MPuhakka** [comment]
Im looking to achieve this at some point

**Comment by eduplus** [comment]
Currently there is only CircleCI supported, but would be great to get other cloud services supported as well. 

Steps to achieve this:

0) as this is first extra service: Add prompt/selection to select which cloud service user wants to use
1) Create bitrise template for RN similar than what we have now for CircleCI
3) Integrate bitrise to github (probably an api call)
